version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    working_directory:  ~/ffc-test
    steps:
      - checkout
      - run:
          name: Install dependencies  # Install with sudo as tests not run as superuser in circleci/python
          command: |
            sudo apt-get update && sudo apt-get install libboost-math-dev
            sudo pip install cmake flake8 numpy pybind11 pytest six --upgrade
      - run:
          name: Install FEniCS dependencies
          command: |
            if [ "${CIRCLE_BRANCH}" == "next" ] ; then export DEP_BRANCH_NAME="next" ; else export DEP_BRANCH_NAME="master" ; fi
            pip install git+https://bitbucket.org/fenics-project/fiat.git@"${DEP_BRANCH_NAME}" --user
            pip install git+https://bitbucket.org/fenics-project/ufl.git@"${DEP_BRANCH_NAME}" --user
            pip install git+https://bitbucket.org/fenics-project/dijitso.git@"${DEP_BRANCH_NAME}" --user
      - run:
          name: Install FFC
          command: pip install -e . --user
      - run:
          name: Install pybind factory
          command: pip install ./libs/ffc-factory/ --user
      - run:
          name: Run unit tests
          command: |
            python -m pytest -v ./test/unit
            python -m pytest -v ./test/uflacs
      - run:
          name: Run regression tests
          command: |
            cd test/regression
            python test.py
